apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ai-api.fullname" . }}
  labels:
    {{- include "ai-api.labels" . | nindent 4 }}
spec:
  {{- if .Values.replicaCount }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.strategy.maxSurge }}
      maxUnavailable: {{ .Values.strategy.maxUnavailable }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  selector:
    matchLabels:
      {{- include "ai-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ai-api.selectorLabels" . | nindent 8 }}
    {{- if .Values.virtualService.enabled }}
      annotations:
        traffic.sidecar.istio.io/excludeOutboundIPRanges: 10.0.0.0/0
        sidecar.istio.io/inject: "true"
    {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "ai-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- if .Values.baseEnv }}
            {{- toYaml .Values.baseEnv | nindent 12 }}
          {{- end }}
          {{- if .Values.env }}
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
          {{ if .Values.command }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
        {{- if and .Values.health .Values.health.path }}
          livenessProbe:
            httpGet:
              path: {{ .Values.health.path }}
              port: http
            failureThreshold: 10
            periodSeconds: 30
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: {{ .Values.health.path }}
              port: http
            failureThreshold: 10
            periodSeconds: 30
            initialDelaySeconds: 60
        {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.modelsPath }}
          volumeMounts:
            - mountPath: {{ .Values.modelsPath }}
              name: models-volume
      volumes:
        - name: models-volume
          emptyDir: {}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}