{{ if gt .Values.scaler.min 1.0 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "ai-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-api.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ai-api.selectorLabels" . | nindent 6 }}
  minAvailable: {{ sub .Values.scaler.min 1 }}
{{- end }}
