{{- if .Values.scaler.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "ai-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-api.labels" . | nindent 4 }}
spec:
  maxReplicas: {{ .Values.scaler.max }}
  minReplicas: {{ .Values.scaler.min }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "ai-api.fullname" . }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.scaler.targetAverageUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.scaler.targetAverageUtilization }}
{{- end }}
