{{- if .Values.virtualService.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "ai-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-api.labels" . | nindent 4 }}
spec:
  hosts:
  {{- toYaml .Values.virtualService.hosts | nindent 2 }}
  gateways:
  - {{ .Values.virtualService.gateway }}
  http:
  - match:
    - uri:
        prefix: "{{ .Values.virtualService.prefix }}"
    rewrite:
      uri: "{{ .Values.virtualService.rewrite }}"
    route:
    - destination:
        host: {{ template "ai-api.fullname" . }}
        port:
          number: {{ .Values.service.port }}
{{- end }}