image:
  repository: 873173223260.dkr.ecr.us-east-1.amazonaws.com/summarizer

virtualService:
  hosts:
    - gateway.contentware.com
    - api.contentware.com

scaler:
  min: 2
  max: 4

env:
  - name: FLASK_ENV
    value: production
  - name: BUCKET_NAME
    value: contentware-nlp-prod
  - name: MODEL_PATH
    value: "summarizer"

tolerations:
  - key: 'nvidia.com/gpu'
    operator: Equal
    value: 'true'
  - key: 'contentware.com/env'
    operator: 'Equal'
    value: 'prod'
    effect: 'PreferNoSchedule'

priorityClassName: 'high'
