image:
  repository: 603599807039.dkr.ecr.us-east-1.amazonaws.com/summarizer

virtualService:
  hosts:
    - ai.dev.contentware.com

strategy:
  maxUnavailable: 1

resources:
  requests:
    memory: 4Gi

env:
  - name: FLASK_ENV
    value: development
  - name: BUCKET_NAME
    value: contentware-nlp
  - name: MODEL_PATH
    value: "summarizer"
