image:
  repository: 873173223260.dkr.ecr.us-east-1.amazonaws.com/summarizer

virtualService:
  hosts:
    - gateway-stage.contentware.com
    - api-stage.contentware.com

env:
  - name: FLASK_ENV
    value: staging
  - name: BUCKET_NAME
    value: contentware-nlp-stage
  - name: MODEL_PATH
    value: "summarizer"
