image:
  repository: 603599807039.dkr.ecr.us-east-1.amazonaws.com/summarizer

virtualService:
  hosts:
    - gateway.dev.contentware.com
    - api.dev.contentware.com

strategy:
  maxUnavailable: 1

scaler:
  max: 1

env:
  - name: FLASK_ENV
    value: development
  - name: BUCKET_NAME
    value: contentware-nlp
  - name: MODEL_PATH
    value: "summarizer"
